[package]
name = "steamlens-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Steam client interop layer for SteamLens"

[package.metadata.release]
tag = false

[dependencies]
libloading = { workspace = true }
steamlens-vdf = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
static_assertions = { workspace = true }
