[package]
name = "steamlens-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Desktop tool for inspecting and modifying Steam achievements and stats"
readme = "../../README.md"

[dependencies]
iced = { workspace = true }
tokio = { workspace = true, features = ["io-util", "io-std", "rt", "sync"] }
reqwest = { workspace = true }
image = { workspace = true }
steamlens-core = { workspace = true }

[[bin]]
name = "steamlens-app"
path = "src/main.rs"
